
[dev]
  port = 8085
  publish = "app"

[[headers]]
	for = "/*"

	[headers.values]
		X-Frame-Options = "DENY"
		X-XSS-Protection = "1; mode=block"
		Content-Security-Policy = "default-src 'self'; connect-src *; img-src *; media-src *; base-uri 'self'"

[[redirects]]
	from = "/*"
	to = "/index.html"
	status = 200

[build]
  functions = "functions"
